In [1]:
import altair as alt
import pandas as pd
import numpy as np

## Merging Native Economic Trends and NIGC data

LLM usage for finding sources of artifacts from cleaning messy pdf and merging with NET data, visual artifacts in charts from jagged data entries.

In [2]:
net = pd.read_excel('../data/native-economic-trends-data_current.xlsx', sheet_name=1)
nigc = pd.read_csv('../data/clean/clean_gaming_report.csv')

In [3]:
crosswalk = pd.read_csv('../data/clean/verified_crosswalk.csv')

In [4]:
nigc.drop_duplicates().shape

(774, 7)

In [5]:
nigc.shape

(831, 7)

In [6]:
nigc.drop_duplicates(inplace=True)

In [7]:
nigc_facility_counts = nigc.loc[:, ['owner_name', 'is_facility']].groupby(
    by=['owner_name']
    ).sum(

    ).sort_values(
        'is_facility', ascending=False
    )
nigc_facility_counts = nigc_facility_counts.loc[nigc_facility_counts['is_facility']>0, :]
# nigc_facility_counts
# These counts are wrong, at least for top 2 nations

In [8]:
nigc_classes_counts_long = nigc.loc[nigc['is_facility'], ['owner_name', 'classes']].groupby(['owner_name', 'classes']).size()
nigc_classes_counts_long = pd.DataFrame(nigc_classes_counts_long).reset_index().rename(columns={0:'count'})
nigc_classes_counts_wide = nigc_classes_counts_long.pivot(index='owner_name', columns='classes', values='count')#.reset_index(drop=True)

nigc_classes_counts_wide.columns.name = None
nigc_classes_counts_wide.reset_index(inplace=True)

nigc_classes_counts_wide.replace(np.nan, 0, inplace=True)

In [9]:
nigc_classes_counts_wide.columns

Index(['owner_name', 'Class II', 'Class II & III', 'Class III', 'Other'], dtype='object')

In [10]:
nigc_classes_counts_wide.loc[:, ['Class II', 'Class II & III', 'Class III', 'Other']] = nigc_classes_counts_wide.loc[:, ['Class II', 'Class II & III', 'Class III', 'Other']].astype(int)
nigc_all_counts = nigc_facility_counts.merge(nigc_classes_counts_wide, on='owner_name')
nigc_all_counts.fillna(0, inplace=True)

cols_to_int = ['is_facility', 'Class II', 'Class II & III', 'Class III', 'Other']
nigc_all_counts[cols_to_int] = nigc_all_counts[cols_to_int].astype(int)

### Applying crosswalk

In [11]:
# crosswalk = crosswalk.loc[:, ['owner_name', 'geoname_mostrecent']]
# crosswalk.drop(columns=['no_reservation_or_not_listed'])

In [12]:
nigc_all_counts = nigc_all_counts.merge(crosswalk, on='owner_name')

The merging at some point erases some reservations that do not own facilities, such as Pine Ridge Reservation. Why?

In [13]:
# Outer join bc we care about non-gaming nations as well, of course
gaming_net_crosswalked = nigc_all_counts.merge(net, on='geoname_mostrecent', how='outer')

gaming_net_crosswalked = gaming_net_crosswalked.loc[
    gaming_net_crosswalked['owner_name'] != 'Quechan Indian Tribe/CA',
    :
    ]

In [14]:
# Drop Navajo nation 1990 due to split into 4 regions
gaming_net_crosswalked = gaming_net_crosswalked.loc[
    ~((gaming_net_crosswalked['geoname_mostrecent'].isin(['Navajo Nation Reservation and Off-Reservation Trust Land',
                                                         'Tohono O\'odham Nation Reservation and Off-Reservation Trust Land',
                                                         'Knik ANVSA',
                                                         'Bois Forte Reservation and Off-Reservation Trust Land'
                                                         ])) & 
    (gaming_net_crosswalked['datayear'] == 1990)),
    :
    ]

In [15]:
# Drop Navajo nation 1990 due to split into 4 regions
gaming_net_crosswalked = gaming_net_crosswalked.loc[
    ~((gaming_net_crosswalked['geoname_mostrecent'].isin(['Mille Lacs Reservation and Off-Reservation Trust Land'
                                                         ])) & 
    (gaming_net_crosswalked['datayear'].isin([1990, 2000]))),
    :
    ]

In [16]:
facility_sums = gaming_net_crosswalked.loc[:, ['geoname_mostrecent', 'is_facility', 
                               'Class II', 'Class II & III', 
                               'Class III', 'Other']].drop_duplicates().groupby(['geoname_mostrecent']).sum().reset_index()

# facility_sums.loc[facility_sums['geoname_mostrecent']=='Pine Ridge Reservation',:]
facility_sums.loc[facility_sums['geoname_mostrecent']=='Navajo Nation Reservation and Off-Reservation Trust Land',:]

,geoname_mostrecent,is_facility,Class II,Class II & III,Class III,Other
434,Navajo Nation Reservation and Off-Reservation ...,5.0,1.0,3.0,1.0,0.0

In [17]:
gaming_net_crosswalked.loc[gaming_net_crosswalked['geoname_mostrecent']=='Kiowa-Comanche-Apache-Fort Sill Apache OTSA',
                           ['owner_name', 'geoname_mostrecent', 'datayear']
                           ]

,owner_name,geoname_mostrecent,datayear
2102,"Comanche Nation, Oklahoma",Kiowa-Comanche-Apache-Fort Sill Apache OTSA,1990.0
2103,"Comanche Nation, Oklahoma",Kiowa-Comanche-Apache-Fort Sill Apache OTSA,2000.0
2104,"Comanche Nation, Oklahoma",Kiowa-Comanche-Apache-Fort Sill Apache OTSA,2010.0
2105,"Comanche Nation, Oklahoma",Kiowa-Comanche-Apache-Fort Sill Apache OTSA,2013.0
2106,"Comanche Nation, Oklahoma",Kiowa-Comanche-Apache-Fort Sill Apache OTSA,2018.0
2107,"Comanche Nation, Oklahoma",Kiowa-Comanche-Apache-Fort Sill Apache OTSA,2020.0
2108,"Comanche Nation, Oklahoma",Kiowa-Comanche-Apache-Fort Sill Apache OTSA,2023.0
2109,Kiowa Tribe of Oklahoma,Kiowa-Comanche-Apache-Fort Sill Apache OTSA,1990.0
2110,Kiowa Tribe of Oklahoma,Kiowa-Comanche-Apache-Fort Sill Apache OTSA,2000.0
2111,Kiowa Tribe of Oklahoma,Kiowa-Comanche-Apache-Fort Sill Apache OTSA,2010.0
2112,Kiowa Tribe of Oklahoma,Kiowa-Comanche-Apache-Fort Sill Apache OTSA,2013.0
2113,Kiowa Tribe of Oklahoma,Kiowa-Comanche-Apache-Fort Sill Apache OTSA,2018.0
2114,Kiowa Tribe of Oklahoma,Kiowa-Comanche-Apache-Fort Sill Apache OTSA,2020.0
2115,Kiowa Tribe of Oklahoma,Kiowa-Comanche-Apache-Fort Sill Apache OTSA,2023.0

In [18]:
gn = gaming_net_crosswalked.merge(facility_sums, on='geoname_mostrecent',
                                  suffixes=['_x', ''])

gn = gn.drop(columns=['owner_name', 'is_facility_x', 
                      'Class II_x', 'Class II & III_x', 
                      'Class III_x', 'Other_x',
                      'no_reservation_or_not_listed'])
gn.shape

(5095, 80)

In [19]:

gn = gn.drop_duplicates()
gn.shape

(5060, 80)

In [20]:
# gn.loc[gn['geoname_mostrecent']=='Kiowa-Comanche-Apache-Fort Sill Apache OTSA',
#                            :
#                            ]

In [21]:
gn.loc[
        gn['geoname_mostrecent']=='Navajo Nation Reservation and Off-Reservation Trust Land',
        :
    ]

,geoname_mostrecent,geoid_mostrecent,geocat_mostrecent,datayear,geoname_datayear,geoid_datayear,geocat_datayear,pop_total,pop_aiana,pop_aianac,...,youthpovshare_total,youthpovshare_aiana,youthpovshare_nhopia,incagg_total,source,is_facility,Class II,Class II & III,Class III,Other
2872,Navajo Nation Reservation and Off-Reservation ...,2430,Federal Reservations/Off-Reservation Trust Lands,2000.0,Navajo Nation,2430,Federal Reservations/Off-Reservation Trust Lands,180462.0,173987.0,175228.0,...,46.586509,47.058578,24.137931,2.331682e+09,2000 decennial census and TIGER/Line shapefiles,5.0,1.0,3.0,1.0,0.0
2873,Navajo Nation Reservation and Off-Reservation ...,2430,Federal Reservations/Off-Reservation Trust Lands,2010.0,Navajo Nation Reservation and Off-Reservation ...,2430,Federal Reservations/Off-Reservation Trust Lands,173667.0,166824.0,169321.0,...,NaN,NaN,NaN,NaN,2010 decennial census and TIGER/Line shapefiles,5.0,1.0,3.0,1.0,0.0
2874,Navajo Nation Reservation and Off-Reservation ...,2430,Federal Reservations/Off-Reservation Trust Lands,2013.0,Navajo Nation,2430,Federal Reservations/Off-Reservation Trust Lands,173998.0,164473.0,166324.0,...,48.711354,49.645458,32.500000,2.473213e+09,2009-2013 American Community Survey and TIGER/...,5.0,1.0,3.0,1.0,0.0
2875,Navajo Nation Reservation and Off-Reservation ...,2430,Federal Reservations/Off-Reservation Trust Lands,2018.0,Navajo Nation Reservation and Off-Reservation ...,2430,Federal Reservations/Off-Reservation Trust Lands,172875.0,166395.0,168027.0,...,48.267133,48.393875,30.769231,2.571186e+09,2014-2018 American Community Survey and TIGER/...,5.0,1.0,3.0,1.0,0.0
2876,Navajo Nation Reservation and Off-Reservation ...,2430,Federal Reservations/Off-Reservation Trust Lands,2020.0,Navajo Nation Reservation and Off-Reservation ...,2430,Federal Reservations/Off-Reservation Trust Lands,165158.0,157901.0,160552.0,...,NaN,NaN,NaN,NaN,2020 decennial census and TIGER/Line shapefiles,5.0,1.0,3.0,1.0,0.0
2877,Navajo Nation Reservation and Off-Reservation ...,2430,Federal Reservations/Off-Reservation Trust Lands,2023.0,Navajo Nation Reservation and Off-Reservation ...,2430,Federal Reservations/Off-Reservation Trust Lands,164533.0,155810.0,159218.0,...,46.423509,46.380765,100.000000,2.815037e+09,2019-2023 American Community Survey and TIGER/...,5.0,1.0,3.0,1.0,0.0

In [22]:
# Tohono O'odham Nation Reservation and Off-Reservation Trust Land
# Knik ANVSA
# Bois Forte Reservation and Off-Reservation Trust Land
# Mille Lacs Reservation and Off-Reservation Trust Land (Also in 2000!)
gn.loc[
        gn['geoname_mostrecent']=='Mille Lacs Reservation and Off-Reservation Trust Land',
        :
    ]

,geoname_mostrecent,geoid_mostrecent,geocat_mostrecent,datayear,geoname_datayear,geoid_datayear,geocat_datayear,pop_total,pop_aiana,pop_aianac,...,youthpovshare_total,youthpovshare_aiana,youthpovshare_nhopia,incagg_total,source,is_facility,Class II,Class II & III,Class III,Other
2689,Mille Lacs Reservation and Off-Reservation Tru...,2270,Federal Reservations/Off-Reservation Trust Lands,2010.0,Mille Lacs Reservation and Off-Reservation Tru...,2270,Federal Reservations/Off-Reservation Trust Lands,4907.0,1598.0,1726.0,...,NaN,NaN,NaN,NaN,2010 decennial census and TIGER/Line shapefiles,2.0,0.0,2.0,0.0,0.0
2690,Mille Lacs Reservation and Off-Reservation Tru...,2270,Federal Reservations/Off-Reservation Trust Lands,2013.0,Mille Lacs,2270,Federal Reservations/Off-Reservation Trust Lands,5189.0,1609.0,1697.0,...,39.105220,41.535777,NaN,1.280336e+08,2009-2013 American Community Survey and TIGER/...,2.0,0.0,2.0,0.0,0.0
2691,Mille Lacs Reservation and Off-Reservation Tru...,2270,Federal Reservations/Off-Reservation Trust Lands,2018.0,Mille Lacs Reservation and Off-Reservation Tru...,2270,Federal Reservations/Off-Reservation Trust Lands,4425.0,1305.0,1460.0,...,34.482759,45.000000,NaN,1.236063e+08,2014-2018 American Community Survey and TIGER/...,2.0,0.0,2.0,0.0,0.0
2692,Mille Lacs Reservation and Off-Reservation Tru...,2270,Federal Reservations/Off-Reservation Trust Lands,2020.0,Mille Lacs Reservation and Off-Reservation Tru...,2270,Federal Reservations/Off-Reservation Trust Lands,4767.0,1515.0,1709.0,...,NaN,NaN,NaN,NaN,2020 decennial census and TIGER/Line shapefiles,2.0,0.0,2.0,0.0,0.0
2693,Mille Lacs Reservation and Off-Reservation Tru...,2270,Federal Reservations/Off-Reservation Trust Lands,2023.0,Mille Lacs Reservation and Off-Reservation Tru...,2270,Federal Reservations/Off-Reservation Trust Lands,4508.0,1117.0,1411.0,...,32.124874,38.809524,NaN,1.450056e+08,2019-2023 American Community Survey and TIGER/...,2.0,0.0,2.0,0.0,0.0

In [23]:
gn['geoname_mostrecent'].value_counts()

geoname_mostrecent
Crow Reservation and Off-Reservation Trust Land         8
Iowa OTSA                                               8
Honolulu Makai Hawaiian Home Land                       8
Menominee Reservation and Off-Reservation Trust Land    8
Makah Indian Reservation                                8
                                                       ..
Ukivok                                                  1
Grouse Creek Group                                      1
Buena Vista Rancheria                                   1
Auwaiolimu-Kalawahine-Kewalo-Papakolea                  1
Wampanoag-Gay Head                                      1
Name: count, Length: 773, dtype: int64

In [24]:
def filter_us_entities(df, keycol = 'geocat_mostrecent'):
    df_filtered = df.loc[
        ~df[keycol].isin(['All states and commonwealths', 'United States (national)']),
        :
    ]

    return df_filtered
# filter_us_entities(gn)

* Remove states, US federal

In [25]:
# gn.to_csv('../data/clean/gaming_net_crosswalked.csv', index=False)

`perpersinc_total`$ = \frac{i_t}{p_t} = \frac{i_a + i_b}{p_a + p_b}$


`perpersinc_aiana`$ = \frac{i_a}{p_a}$, where we know $i_a, i_t, p_a, p_t$ and the named vars, but want to find $i_b, p_b$.

## Visualizations

In [26]:
# cols_to_fillna = ['is_facility', 'Class II', 'Class II & III', 'Class III', 'Other']
# gn.loc[:, cols_to_fillna] = gn.loc[:, cols_to_fillna].fillna(0)

In [27]:
# gaming_net_crosswalked = pd.read_csv('../data/clean/gaming_net_crosswalked.csv')

In [28]:
'Pine Ridge Reservation' in gn['geoname_mostrecent'].tolist()

True

In [ ]:
data_for_bar = gaming_net_crosswalked.copy()

data_for_bar = data_for_bar.loc[(data_for_bar['is_facility']>0) & (data_for_bar['datayear']==2020), :]

In [28]:
# alt.Chart(data_for_bar).mark_bar().encode(
#     x = alt.X('owner_name:N'),
#     y = alt.Y('is_facility')
# )

In [ ]:
# gaming_net_crosswalked.loc[
#         gaming_net_crosswalked['is_facility'].isna(), 
#         ['is_facility','Class II', 'Class II & III', 'Class III', 'Other']
#     ] = 0

In [29]:
# gaming_net_crosswalked['geoname_abbrev'] = gaming_net_crosswalked['geoname_mostrecent'].str.removesuffix(
gn['geoname_abbrev'] = gn['geoname_mostrecent'].str.removesuffix(
        ' Indian Reservation and Off-Reservation Trust Land'
    ).str.removesuffix(
        ' Reservation and Off-Reservation Trust Land'
    ).str.removesuffix(
        ' and Off-Reservation Trust Land'
    ).str.removesuffix(
        ' Reservation'
    )

In [31]:
# gaming_net_crosswalked.iloc[3084, [6]].str.removesuffix(' Indian Reservation and Off-Reservation Trust Land')

### 1a. Are gaming facilities associated with different incomes in different populations? 

This could honestly be a bar chart, but that might be deceptive comparing mean incomes with very different sample sizes. Much less data for large facility counts.

In [ ]:
data_income_pop = gaming_net_crosswalked.copy()
data_income_pop = data_income_pop.loc[
    data_income_pop['datayear']==2018, 
    ['owner_name', 'geoname_mostrecent', 'geoname_abbrev', 'hincmed_total', 'hincmed_aiana','is_facility']
    ]

American Indian or Alaska Native alone (AIANa)

Native Hawaiian and Other Pacific Islander alone (NHOPIa)

In [34]:
data_income_pop_long = data_income_pop.melt(
    id_vars=['owner_name', 'geoname_mostrecent', 'geoname_abbrev', 'is_facility'],
    value_vars=['hincmed_total', 'hincmed_aiana'],
    var_name='hinc_type',
    value_name='hinc_value'
)

In [35]:
data_income_pop_long = data_income_pop_long.replace('hincmed_total', 'Total').replace('hincmed_aiana', 'AIANa')

In [36]:
# data_income_pop_long.loc[:, ['geoname_mostrecent', 'is_facility']]['geoname_mostrecent']

In [86]:
# gn.loc[gn['geoname_mostrecent'], :]

In [37]:
# For each geoname (reservation), sum their facilities.
# Then, join that back with data_income_pop_long and bar chart :)
geoname_facility_sums = data_income_pop_long.loc[:, ['geoname_mostrecent', 'geoname_abbrev', 'is_facility']].drop_duplicates(
    
).groupby(by=['geoname_mostrecent', 'geoname_abbrev']).sum()

geoname_facility_sums = geoname_facility_sums.reset_index().rename(columns={'is_facility':'num_res_facilities'})
geoname_facility_owns = geoname_facility_sums.rename(columns={'num_res_facilities':'owns_facility'})
geoname_facility_owns['owns_facility'] = geoname_facility_owns['owns_facility'] > 0
geoname_facility_owns

,geoname_mostrecent,geoname_abbrev,owns_facility
0,Acoma Pueblo and Off-Reservation Trust Land,Acoma Pueblo,True
1,Adai Caddo SDTSA,Adai Caddo SDTSA,False
2,Agua Caliente Indian Reservation and Off-Reser...,Agua Caliente,True
3,Akhiok ANVSA,Akhiok ANVSA,False
4,Akiachak ANVSA,Akiachak ANVSA,False
...,...,...,...
743,Yomba Reservation,Yomba,False
744,Ysleta del Sur Pueblo and Off-Reservation Trus...,Ysleta del Sur Pueblo,True
745,Yurok Reservation,Yurok,True
746,Zia Pueblo and Off-Reservation Trust Land,Zia Pueblo,False
747,Zuni Reservation and Off-Reservation Trust Land,Zuni,False

In [38]:
# bar_income_pop = (
#     alt.Chart(data_income_pop_long.merge(geoname_facility_owns))
#     .mark_bar(filled=True, size=50, opacity=0.8)
#     .encode(
#         x=alt.X('owns_facility').title('Owns a gaming facility'),
#         xOffset='hinc_type',
#         y=alt.Y('hinc_value').title('Median household income'),
#         color=alt.Color('hinc_type').scale(
#             scheme='set2'
#             ).title(
#                 'Population group'
#             ).legend(
#                 alt.Legend(fillColor='rgba(255, 255, 255, 0.5)', 
#                            cornerRadius=5,
#                            padding=7)
#             )
#     )
# )

# # Federal median household income in 2018
# datum_income_pop = alt.Chart().mark_rule(color='black', strokeDash=[3,3], strokeWidth=3).encode(
#     y=alt.datum(61937)
# )

# bar_chart_income_pop = bar_income_pop + datum_income_pop

# bar_chart_income_pop.resolve_scale(color='shared').properties(
#     height=300,
#     width=500,
#     title=alt.Title(['Do reservations with any nations that own gaming investments', 'experience greater wealth?'],
#                     anchor='start',
#                     subtitle='Compare household incomes on reservations against the 2018 federal average of $61,937 (dotted line)',
#                     # align='center',
#                     fontSize=22,
#                     dx=25)
# ).configure(
#     font='Agency FB',
# ).configure_axis(
#     labelFontSize=14,
#     titleFontSize=16,
# ).configure_legend(
#     titleFontSize=15,
#     labelFontSize=15,
#     titleAnchor='middle',
#     titleAlign='center',
#     orient='top-right'
# )#.save('./graphics/bar_income_vs_ownsfacility.svg')

### 1b. Is the number of gaming facilities associated with different incomes in different populations?

NOTE: This has been double-plotting reservations.

In [39]:
data_res_income_pop_long = data_income_pop_long.merge(
    geoname_facility_sums
    ).loc[:, ['geoname_mostrecent', 'geoname_abbrev', 'hinc_type', 'hinc_value', 'num_res_facilities']].drop_duplicates(

    )
# data_res_income_pop_long.loc[data_res_income_pop_long['geoname_mostrecent']=='Acoma Pueblo and Off-Reservation Trust Land', :]
jitter_radius = 0.15
data_res_income_pop_long['jitter'] = np.where(data_res_income_pop_long['hinc_type']=='Total', jitter_radius, -jitter_radius)

res_exclude_list = ['Redding Rancheria',
                    'Sulphur Bank Rancheria',
                    # 'Shakopee Mdewakanton Sioux Community and Off-Reservation Trust Land'
                    ]
data_res_income_pop_long = data_res_income_pop_long.loc[
        ~data_res_income_pop_long['geoname_mostrecent'].isin(res_exclude_list),
        :
    ]

In [40]:
data_res_income_pop_long.sort_values(by='hinc_value', ascending=True)

,geoname_mostrecent,geoname_abbrev,hinc_type,hinc_value,num_res_facilities,jitter
1068,Klamath Reservation,Klamath,AIANa,11187.070116,1.0,-0.15
1353,Shageluk ANVSA,Shageluk ANVSA,AIANa,11628.776756,0.0,-0.15
314,Klamath Reservation,Klamath,Total,11628.776756,1.0,0.15
1378,Southeastern Mvskoke Nation SDTSA,Southeastern Mvskoke Nation SDTSA,AIANa,15926.922146,0.0,-0.15
356,Lovelock Indian Colony,Lovelock Indian Colony,Total,16685.347011,0.0,0.15
...,...,...,...,...,...,...
1472,Waimea Hawaiian Home Land,Waimea Hawaiian Home Land,AIANa,NaN,0.0,-0.15
1474,Waiohinu Hawaiian Home Land,Waiohinu Hawaiian Home Land,AIANa,NaN,0.0,-0.15
1475,Waiohuli (Residential) Hawaiian Home Land,Waiohuli (Residential) Hawaiian Home Land,AIANa,NaN,0.0,-0.15
1481,Washoe Ranches Trust Land,Washoe Ranches Trust Land,AIANa,NaN,1.0,-0.15
1501,Yavapai-Prescott Reservation,Yavapai-Prescott,AIANa,NaN,2.0,-0.15

In [42]:
pop_colors = ['darkturquoise', 'chocolate']
pop_color_scale = alt.Scale(domain=['AIANa', 'Total'], range=pop_colors)
# lightseagreen
# aquamarine
# darkturquoise
# mediumturquoise
# skyblue
# turquoise

# coral
# chocolate
# peru
# sandybrown
# sienna

# pop_color_scheme = dict(zip(['AIANa', 'Total'], ['mediumaquamarine', 'chocolate']))

In [43]:
# AI: ChatGPT for finding likely sources of graphical artifacts in messy data
# "why is loess zig-zag after altair .transform_loess()"
manual_xticks = list(range(0,1+data_res_income_pop_long['num_res_facilities'].max().astype(int)))
manual_xticks_minor = manual_xticks[1::2]
# shared_color = alt.Color('hinc_type:N', title='Population group').scale(pop_color_scale)
shared_color = alt.Color('hinc_type:N', title='Population group').scale(range=pop_colors)
# Oh! Specifically entering the color/pop domain makes Altair think it is a
## different domain from the one shape uses! They are the same

grid_layer = (
    alt.Chart(pd.DataFrame({'x': manual_xticks_minor}))
    .mark_rule(color='lightgray', size=0.5)
    .encode(x='x:Q')
)

scatter_income_pop = (
    alt.Chart(data_res_income_pop_long)
    .transform_calculate(
        num_res_facilities_jitter='datum.num_res_facilities + datum.jitter'
    )
    .mark_point(filled=False, size=20, strokeWidth=2, opacity=0.48)
    .encode(
        x=alt.X('num_res_facilities_jitter:Q').title(
            'Number of gaming facilities'
            ).axis(
                values=manual_xticks,
            ).scale(
                padding=0
        ),
        # xOffset=alt.XOffset('jitter:Q'),
        y=alt.Y('hinc_value').title('Median household income'),
        color=shared_color,
        shape=alt.Shape('hinc_type:N', title='Population group').scale(
            # domain=['AIANa', 'Total'],
            range=['triangle-left', 'triangle-right']
            ),
        order=alt.Order('hinc_type:N', sort='descending')
    )
)

loess_opacity = 0.85
loess_income_pop = (
    alt.Chart(data_res_income_pop_long)
    .transform_loess(
        'num_res_facilities', 'hinc_value', groupby=['hinc_type']
    )
    .mark_line(filled=False, size=4, opacity=loess_opacity)
    .encode(
        x=alt.X('num_res_facilities:Q'),
        y=alt.Y('hinc_value'),
        color=shared_color.legend(None),
    )
)

# Federal median household income in 2018
datum_income_pop = alt.Chart().mark_rule(color='black', strokeDash=[3,3], strokeWidth=3).encode(
    y=alt.datum(61937)
)

# Annotate the wealthiest nation
annotations = alt.Chart(data_res_income_pop_long).transform_calculate(
        num_res_facilities_jitter='datum.num_res_facilities + datum.jitter'
    ).mark_text(
    align='left',
    baseline='middle',
    dx=5,
    dy=2,
    fontSize=13,
    # fontWeight='bold',
).encode(
    x='num_res_facilities_jitter:Q',
    y='hinc_value',
    text='geoname_abbrev',
    color=shared_color.legend(None),
).transform_filter(
    alt.FieldOneOfPredicate(field='geoname_abbrev', oneOf=['Shakopee Mdewakanton Sioux Community'])
)


chart_income_pop = grid_layer + datum_income_pop + scatter_income_pop + loess_income_pop + annotations


chart_income_pop.properties(
    height=300,
    width=500,
    title=alt.Title(['Do reservations with many gaming investments', 'experience greater wealth?'],
                    anchor='start',
                    subtitle='Household incomes on reservations (colored lines) consistently trended below the 2018 federal average of $61,937 (dotted line)',
                    subtitleFontSize=13,
                    # align='center',
                    fontSize=22,
                    dx=25
                    )
).configure(
    font='Agency FB',
).configure_axis(
    labelFontSize=14,
    titleFontSize=16,
).configure_legend(
    titleFontSize=15,
    labelFontSize=15,
    titleAnchor='middle',
    titleAlign='center',
    orient='top-right',
    fillColor='rgba(255, 255, 255, 0.50)', 
    cornerRadius=25,
    padding=28
).resolve_scale(
    xOffset='independent',
    color='independent',
    shape='independent'
)#.save('./graphics/scatter_income_vs_facilitycount.svg')

alt.LayerChart(...)

In [44]:
# TODO:
# Redo as bar chart with error bars, one bar per Number of gaming facilities

### 2. State poverty level compared to Indian nations' poverty levels

In [76]:
'Pine Ridge Reservation' in gaming_net_crosswalked['geoname_mostrecent'].tolist()

True

In [77]:
gaming_net_crosswalked.loc[gaming_net_crosswalked['geoname_mostrecent']=='Pine Ridge Reservation', :]

,owner_name,is_facility,Class II,Class II & III,Class III,Other,geoname_mostrecent,no_reservation_or_not_listed,geoid_mostrecent,geocat_mostrecent,...,perpersinc_nhopia,povshare_total,povshare_aiana,povshare_nhopia,youthpovshare_total,youthpovshare_aiana,youthpovshare_nhopia,incagg_total,source,geoname_abbrev
3438,NaN,0.0,0.0,0.0,0.0,0.0,Pine Ridge Reservation,NaN,2810,Federal Reservations/Off-Reservation Trust Lands,...,NaN,62.641986,76.374095,NaN,70.670391,72.963469,NaN,1.014844e+08,1990 decennial census and TIGER/Line shapefiles,Pine Ridge
3439,NaN,0.0,0.0,0.0,0.0,0.0,Pine Ridge Reservation,NaN,2810,Federal Reservations/Off-Reservation Trust Lands,...,0.0,53.412073,54.743847,NaN,60.908956,61.245136,NaN,1.689578e+08,2000 decennial census and TIGER/Line shapefiles,Pine Ridge
3440,NaN,0.0,0.0,0.0,0.0,0.0,Pine Ridge Reservation,NaN,2810,Federal Reservations/Off-Reservation Trust Lands,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2010 decennial census and TIGER/Line shapefiles,Pine Ridge
3441,NaN,0.0,0.0,0.0,0.0,0.0,Pine Ridge Reservation,NaN,2810,Federal Reservations/Off-Reservation Trust Lands,...,NaN,48.990924,53.362322,NaN,57.128500,59.249496,NaN,2.694033e+08,2009-2013 American Community Survey and TIGER/...,Pine Ridge
3442,NaN,0.0,0.0,0.0,0.0,0.0,Pine Ridge Reservation,NaN,2810,Federal Reservations/Off-Reservation Trust Lands,...,NaN,48.099847,52.244035,NaN,57.848472,60.103222,NaN,2.704459e+08,2014-2018 American Community Survey and TIGER/...,Pine Ridge
3443,NaN,0.0,0.0,0.0,0.0,0.0,Pine Ridge Reservation,NaN,2810,Federal Reservations/Off-Reservation Trust Lands,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020 decennial census and TIGER/Line shapefiles,Pine Ridge
3444,NaN,0.0,0.0,0.0,0.0,0.0,Pine Ridge Reservation,NaN,2810,Federal Reservations/Off-Reservation Trust Lands,...,NaN,48.659939,52.081766,NaN,52.899426,54.273156,NaN,2.515422e+08,2019-2023 American Community Survey and TIGER/...,Pine Ridge

In [ ]:
gaming_net_crosswalked['is']

In [75]:
# gaming_net_crosswalked.loc[gaming_net_crosswalked['geoname_mostrecent'].str.extract('(\(state\))'), :]

In [67]:
gaming_net_crosswalked.loc[gaming_net_crosswalked['owner_name'].isna() & (gaming_net_crosswalked['geoname_mostrecent'].str.contains('(state)')), 
                           'geoname_mostrecent'].unique()

C:\Users\riley\AppData\Local\Temp\ipykernel_21104\2445367112.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  gaming_net_crosswalked.loc[gaming_net_crosswalked['owner_name'].isna() & (gaming_net_crosswalked['geoname_mostrecent'].str.contains('(state)')),

array(['Alabama (state)', 'Alaska (state)', 'Arizona (state)',
       'Arkansas (state)', 'California (state)', 'Colorado (state)',
       'Connecticut (state)', 'Delaware (state)',
       'District of Columbia (state)', 'Florida (state)',
       'Georgia (state)', 'Golden Hill Paugussett (state) Reservation',
       'Hassanamisco (state) Reservation', 'Hawaii (state)',
       'Idaho (state)', 'Illinois (state)', 'Indiana (state)',
       'Iowa (state)', 'Kansas (state)', 'Kentucky (state)',
       'Louisiana (state)', 'MOWA Choctaw (state) Reservation',
       'Maine (state)', 'Maryland (state)', 'Massachusetts (state)',
       'Mattaponi (state) Reservation', 'Michigan (state)',
       'Minnesota (state)', 'Mississippi (state)', 'Missouri (state)',
       'Montana (state)', 'Nebraska (state)', 'Nevada (state)',
       'New Hampshire (state)', 'New Jersey (state)',
       'New Mexico (state)', 'New York (state)', 'North Carolina (state)',
       'North Dakota (state)', 'Ohio (state)', 'Oklahoma (state)',
       'Oregon (state)', 'Pamunkey (state) Reservation',
       'Paucatuck Eastern Pequot (state) Reservation',
       'Pennsylvania (state)', 'Poospatuck (state) Reservation',
       'Princess Kahanu Estates Hawaiian Home Land',
       'Rhode Island (state)', 'Schaghticoke (state) Reservation',
       'Shinnecock (state) Reservation', 'South Carolina (state)',
       'South Dakota (state)', 'Tama (state) Reservation',
       'Tennessee (state)', 'Texas (state)', 'Utah (state)',
       'Vermont (state)', 'Virginia (state)', 'Washington (state)',
       'West Virginia (state)', 'Wisconsin (state)', 'Wyoming (state)'],
      dtype=object)

In [47]:
poverty_levels = gaming_net_crosswalked.dropna(subset=['owner_name', 'geoname_mostrecent']).copy() # Issue, big issue lol
poverty_levels = poverty_levels.merge(nigc.loc[:,['owner_name', 'owner_state']], on='owner_name', how='left')
poverty_levels.dropna(subset=['datayear'], inplace=True)
poverty_levels = poverty_levels.loc[:, ['owner_name', 'owner_state', 'datayear', 'povshare_total']].drop_duplicates()
poverty_levels['datayear_dt'] = pd.to_datetime(poverty_levels['datayear'].astype(int), format='%Y')

In [49]:
# Many issues with states. Drop the nonsense ones
abbreviations = [
    # https://en.wikipedia.org/wiki/List_of_states_and_territories_of_the_United_States#States.
    "AK", "AL", "AR", "AZ", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "IA",
    "ID", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "ME", "MI", "MN", "MO",
    "MS", "MT", "NC", "ND", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "OK",
    "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WI",
    "WV", "WY",
]

In [58]:
# gaming_net_crosswalked.loc[gaming_net_crosswalked['geoname_mostrecent']=='Pine Ridge Reservation', 
#                            ['geoname_mostrecent', 'owner_name']]

In [35]:
poverty_levels = poverty_levels.loc[poverty_levels['owner_state'].isin(abbreviations), :]

In [53]:

'Pine Ridge Reservation' in poverty_levels['owner_name'].tolist()

False

In [55]:

'Pine Ridge Reservation' in gaming_net_crosswalked['geoname_mostrecent'].tolist()

True

There are far too many states to put on here. Just choose the 3 states with the most facilities.

In [36]:
states_5_most_facilities = nigc['owner_state'].value_counts()[:4].index.tolist()

In [37]:
states_5_most_facilities

['OK', 'CA', 'PO', 'AZ']

In [38]:
poverty_levels_top = poverty_levels.loc[poverty_levels['owner_state'].isin(states_5_most_facilities), :]

In [39]:
# spaghetti_poverty = alt.Chart(poverty_levels_top).mark_bar().encode(
#     x=alt.X(
#         'datayear_dt:O',
#         title='Year',
#         timeUnit='year',
#         axis=alt.Axis(format='%Y')
#     ),
#     y=alt.Y('max(povshare_total):Q'),
#     color=alt.Color('owner_state:N'),
#     xOffset='owner_state:N'
# )
# spaghetti_poverty

In [165]:

'Pine Ridge Reservation' in poverty_levels['owner_name'].tolist()

False

In [78]:
strip_poverty = alt.Chart(poverty_levels).mark_tick(
        color='black',
    ).encode(
        x=alt.X('povshare_total').title('Percentage of total population in poverty'),
        y=alt.Y('datayear:O').title('Year'),
        # color=alt.Color('owner_state')
)
median_datum = alt.Chart(poverty_levels).mark_tick(
        color='mediumseagreen', 
        strokeDash=[5,5],
        thickness=6,
        # size=20,
        cornerRadius=3,
        opacity=0.95
    ).encode(
        x=alt.X('median(povshare_total):Q'),
        y=alt.Y('datayear:O'),
        # color='datayear'
    )

chart_poverty = strip_poverty + median_datum

chart_poverty.properties(
    height=300,
    width=500,
    title=alt.Title(['Has reservation poverty gotten less pervasive', 'over the years?'],
                    anchor='start',
                    subtitle='Each strip is a reservation statistical area. Median reservation poverty rates are indicated by green lines.',
                    # align='center',
                    fontSize=22,
                    subtitleFontSize=15,
                    dx=25)
).configure(
    font='Agency FB',
).configure_axis(
    labelFontSize=14,
    titleFontSize=16,
).configure_legend(
    titleFontSize=15,
    labelFontSize=15,
    titleAnchor='middle',
    titleAlign='center',
    orient='top-right'
)#.save('./graphics/strip_poverty_vs_year.svg')

alt.LayerChart(...)

### 3. States vs. the Nations they share borders with

In [41]:
gaming_net_crosswalked_state = gaming_net_crosswalked.merge(nigc.loc[:, ['owner_name','owner_state']], 
                                                            on='owner_name',
                                                            how='left')

In [42]:
gaming_net_crosswalked_state['geocat_mostrecent'].value_counts()

geocat_mostrecent
Federal Reservations/Off-Reservation Trust Lands      4965
Alaska Native Village Statistical Areas (ANVSAs)      1540
Oklahoma Tribal Statistical Areas (OTSAs)             1108
Hawaiian Home Lands (HHLs)                             435
All states and commonwealths                           362
State-designated Tribal Statistical Areas (SDTSAs)     182
Tribally Designated Statistical Areas (TDSAs)           73
State Reservations                                      71
Oklahoma Joint-Use Areas                                25
Federal Joint-Use Areas                                 20
United States (national)                                 7
Name: count, dtype: int64

In [ ]:
# Get all states, and get all nations with gaming facilities
gaming_net_crosswalked_state = gaming_net_crosswalked_state.loc[
    (~gaming_net_crosswalked_state['geocat_mostrecent'].isin(['United States (national)'])) ,
    :
]

gaming_net_crosswalked_state = gaming_net_crosswalked_state.loc[
    (gaming_net_crosswalked_state['geocat_mostrecent']=='All states and commonwealths') | (gaming_net_crosswalked_state['is_facility']>0),
    :
].drop_duplicates()

In [44]:
is_us_state = np.where(gaming_net_crosswalked_state['geocat_mostrecent']=='All states and commonwealths', True, False)
gaming_net_crosswalked_state['is_us_state'] = is_us_state

In [45]:
abbreviation_to_name = {
    # https://en.wikipedia.org/wiki/List_of_states_and_territories_of_the_United_States#States.
    "AK": "Alaska",
    "AL": "Alabama",
    "AR": "Arkansas",
    "AZ": "Arizona",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DE": "Delaware",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "IA": "Iowa",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "MA": "Massachusetts",
    "MD": "Maryland",
    "ME": "Maine",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MO": "Missouri",
    "MS": "Mississippi",
    "MT": "Montana",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "NE": "Nebraska",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NV": "Nevada",
    "NY": "New York",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VA": "Virginia",
    "VT": "Vermont",
    "WA": "Washington",
    "WI": "Wisconsin",
    "WV": "West Virginia",
    "WY": "Wyoming",
}

In [46]:
name_to_abbreviation = {value: key for key, value in abbreviation_to_name.items()}

In [47]:
gaming_net_crosswalked_state.loc[
        gaming_net_crosswalked_state['is_us_state'],
        'owner_state'
    ] = gaming_net_crosswalked_state.loc[
        gaming_net_crosswalked_state['is_us_state'],
        'geoname_mostrecent'
    ].str.replace(' (state)', '').map(name_to_abbreviation)

In [48]:
gaming_net_crosswalked_state.loc[
    gaming_net_crosswalked_state['is_us_state'],
    'owner_name'
] = gaming_net_crosswalked_state.loc[
        gaming_net_crosswalked_state['is_us_state'],
        'geoname_mostrecent'
    ]

In [49]:
gaming_net_crosswalked_state['owner_state_full'] = gaming_net_crosswalked_state['owner_state'].map(abbreviation_to_name)

In [50]:
# gaming_net_crosswalked_state['owner_state'].value_counts()

gaming_net_crosswalked_state['owner_state'][gaming_net_crosswalked_state['owner_state'].isin(abbreviation_to_name.keys())]

0       NM
3       NM
6       NM
9       NM
12      NM
        ..
8774    CA
8776    CA
8792    OK
8795    OK
8797    CA
Name: owner_state, Length: 1736, dtype: object

In [91]:
# gaming_net_crosswalked_state.loc[
#     (gaming_net_crosswalked_state['owner_state'].isin(['MT', 'OR', 'WA'])) & (gaming_net_crosswalked_state['datayear'].isin([2023])),
#     :
# ].dropna(subset=['unemp_total'])

In [102]:
# lightseagreen
# aquamarine
# darkturquoise
# mediumturquoise
# skyblue
# turquoise
# teal

# coral
# chocolate
# peru
# sandybrown
# sienna
region_colors = ['cadetblue', 'coral']

In [110]:
gaming_net_crosswalked_state.loc[
    (gaming_net_crosswalked_state['owner_state'].isin(['WY'])) & (gaming_net_crosswalked_state['datayear'].isin([2023])),
    ['owner_name', 'geoname_mostrecent', 'unemp_total', 'unemp_aiana']
]#.dropna(subset=['unemp_total'])

,owner_name,geoname_mostrecent,unemp_total,unemp_aiana
8543,Northern Arapaho Tribe of the Wind River India...,Wind River Reservation and Off-Reservation Tru...,7.988260,19.364059
8558,Shoshone Tribe of the Wind River Indian Reserv...,Wind River Reservation and Off-Reservation Tru...,7.988260,19.364059
8651,Wyoming (state),Wyoming (state),3.742766,12.767541

In [104]:
bar_unemployment = alt.Chart(gaming_net_crosswalked_state.loc[
    (gaming_net_crosswalked_state['owner_state'].isin(['MT', 'OR', 'WA', 'WY'])) & (gaming_net_crosswalked_state['datayear'].isin([2023])),
    :
].dropna(subset=['unemp_total']) # Snoqualmie in WA is all NA
).mark_bar().encode(
    x=alt.X('geoname_abbrev', sort='-y').title('').axis(labelAngle=-75),
    y=alt.Y('unemp_total').title('Unemployment Rate'),
    facet=alt.Facet('owner_state_full').title(''),
    fill=alt.Fill('is_us_state').scale(range=region_colors).legend(None)
).resolve_scale(x='independent')

bar_unemployment.properties(
    height=300,
    width=250,
    title=alt.Title(['Northwestern reservations exceed nearby state unemployment rates in 2023'],
                    anchor='start',
                    subtitle='State-wide unemployment rates are highlighted',
                    # align='center',
                    fontSize=22,
                    subtitleFontSize=15,
                    dx=25,
                    dy=-20)
).configure(
    font='Agency FB',
).configure_axis(
    labelFontSize=14,
    titleFontSize=16,
).configure_headerFacet(
    labelFontSize=18
)#.save('./graphics/bar_state_facet_unemployment_vs_reservation.svg')
# Texture for state vs. nation, top X unemployment rates, facet by year?

alt.Chart(...)

### 4 and 5. Zooming in on Montana Nations: Bump Chart?

In [52]:
mt = gaming_net_crosswalked_state.loc[
        (gaming_net_crosswalked_state['owner_state']=='MT'), 
        :
    ]

#  & (gaming_net_crosswalked_state['datayear']==2023)

In [53]:
mt['datayear'] = pd.to_datetime(mt['datayear'], format='%Y')

C:\Users\riley\AppData\Local\Temp\ipykernel_18064\3445572462.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mt['datayear'] = pd.to_datetime(mt['datayear'], format='%Y')

In [54]:
homeownership_rank = alt.Chart(mt).mark_line(point=True, filled=False).encode(
    x=alt.X('datayear:T').title('Year'),
    y=alt.Y('rank_val:O').title('Rank'),
    color=alt.Color('geoname_mostrecent:N').title('Reservation/State'),
    detail='geoname_mostrecent:N',
).transform_window(
    rank_val='rank()',
    sort=[
        alt.SortField('ownoccshare_aiana', order='descending')
    ],
    groupby=['datayear'],
).properties(
    width=500,
    height=200,
    title=alt.Title(['MT and reservations ranked by AIANa house ownership'],
                    anchor='start',
                    subtitle='Off-reservation AIANa people living in houses own the house less frequently than do AIANa people on reservations',
                    # align='center',
                    fontSize=22,
                    dx=25
                    )
)

homeownership_rank.configure(
    font='Agency FB',
).configure_axis(
    labelFontSize=14,
    titleFontSize=16,
).configure_legend(
    titleFontSize=15,
    labelFontSize=15,
    titleAnchor='middle',
    titleAlign='right',
    # orient='top-right'
)#.save('./graphics/rank_mt_houseownership_vs_year.svg')

alt.Chart(...)

In [55]:
mt.loc[mt['geoname_mostrecent']=='Montana (state)', ['datayear', 'hincmed_total']]

       datayear  hincmed_total
4756 1990-01-01   53609.587729
4757 2000-01-01   58438.080046
4758 2010-01-01            NaN
4759 2013-01-01   60469.490463
4760 2018-01-01   63779.283893
4761 2020-01-01            NaN
4762 2023-01-01   69922.000000

In [56]:
mt_long = mt.melt(
    id_vars = ['geoname_mostrecent', 'datayear'],
    value_vars = ['povshare_aiana', 'povshare_total', 
                  'hincmed_aiana', 'hincmed_total',
                  'ownoccshare_aiana', 'ownoccshare_total'],
    var_name = 'pop_group',
    value_name = 'value'
)

In [57]:
mt_long['population_group'] = mt_long['pop_group'].str.extract(r'_(aiana|total)$')

In [58]:
mt_long['outcome'] = mt_long['pop_group'].str.extract(r'^(povshare|hincmed|ownoccshare)')

In [59]:
mt_Long = mt_long.pivot_table(
    index=['datayear', 'geoname_mostrecent', 'population_group'],
    columns='outcome',
    values='value'
).reset_index()

In [60]:
# mt_long.loc[mt_long['pop_group']=='ownoccshare_total', :]

In [61]:
mt_long_ = mt_long.copy()
mt_long_['outcome'] = mt_long_['outcome'].str.replace('ownoccshare', '% of homes occupied by owner')
mt_long_['outcome'] = mt_long_['outcome'].str.replace('povshare', '% in poverty')
mt_long_['outcome'] = mt_long_['outcome'].str.replace('hincmed', 'Median household income')

In [62]:
# ownoccshare_aianac
color_total = 'rgb(201, 134, 64)'
color_aiana = 'rgb(64, 187, 201)'

mt_facet_povshare_aiana = alt.Chart(mt_long_).mark_line(color=color_aiana, opacity=0.5).encode(
    x=alt.X('datayear:T', ).title('Year'),
    y=alt.Y('value').title(''),
    color=alt.Color('population_group').title('Population group'),
    detail=alt.Detail('geoname_mostrecent:N'),
    row=alt.Row('outcome').title('Socioeconomic outcome')
).resolve_scale(
    y='independent'
).properties(
    height=100,
    width=500,
    title=alt.Title(['AIANa populations consistently behind', 'in socioeconomic measures on MT reservations'],
                    anchor='start',
                    subtitle='Across Montana reservations, native-identifying peoples\' outcomes lag. Each line represents a reservation.',
                    # align='center',
                    fontSize=22,
                    subtitleFontSize=15,
                    dx=25)
)

mt_facet_povshare_aiana.configure(
    font='Agency FB',
).configure_axis(
    labelFontSize=14,
    titleFontSize=16,
).configure_legend(
    titleFontSize=15,
    labelFontSize=15,
    titleAnchor='middle',
    titleAlign='center',
    orient='right'
).configure_headerRow(
    labelFontSize=20,
    titleFontSize=20,
    labelAngle=0,
    labelAlign='left',
    labelAnchor='middle',
    labelOrient='left'
)#.save('./graphics/line_mt_outcome_facet_outcome_vs_year.svg')

alt.Chart(...)

* Replace with bars, explain why missing in annotation

In [63]:
# nigc_mt = nigc.loc[(nigc['owner_state']=='MT') & (nigc['is_facility']), :]
# nigc_mt = nigc_mt.merge(crosswalk, on='owner_name')
# mt_nations = nigc_mt.merge(net, on='geoname_mostrecent').drop_duplicates()
# mt_state = net.loc[net['geoname_mostrecent']=='Montana (state)', :]

### 6 and 7. Scatter plots: Gaming vs. No Gaming

In [64]:
gaming_compare = gaming_net_crosswalked.copy()

In [65]:
gaming_compare['geocat_mostrecent'].value_counts()

geocat_mostrecent
Federal Reservations/Off-Reservation Trust Lands      2250
Alaska Native Village Statistical Areas (ANVSAs)      1526
Hawaiian Home Lands (HHLs)                             435
All states and commonwealths                           362
Oklahoma Tribal Statistical Areas (OTSAs)              195
State-designated Tribal Statistical Areas (SDTSAs)     182
State Reservations                                      71
Tribally Designated Statistical Areas (TDSAs)           43
Oklahoma Joint-Use Areas                                25
Federal Joint-Use Areas                                 20
United States (national)                                 7
Name: count, dtype: int64

In [66]:
gaming_compare = gaming_compare.loc[
    ~gaming_compare['geocat_mostrecent'].isin(['All states and commonwealths', 'United States (national)']),
    :
]

In [67]:
gaming_compare['has_facility'] = np.where(gaming_compare['is_facility']>0, 'Has facility', 'Doesn\'t have facility')

In [68]:
gaming_compare23 = gaming_compare.loc[gaming_compare['datayear']==2023, :]

In [69]:
scatter_incomes = alt.Chart(gaming_compare23).mark_point(filled=True, opacity=0.8).encode(
    x=alt.X('hincmed_aiana').title('Median income'),
    y=alt.Y('educshare_aiana_bachplus').title('Percentage of adults 25+ with bachelor\'s or higher'),
    color=alt.Color('has_facility:N').legend(
                alt.Legend(fillColor='rgba(255, 255, 255, 0.5)', 
                           cornerRadius=5,
                           padding=7,
                           title='Nation ownership')
            )#.scale(scheme='blueorange'),
    # size=alt.Size('is_facility')
)

scatter_incomes.properties(
    height=300,
    width=500,
    title=alt.Title(['Do wealth and gaming facility ownership affect reservations\'', 'educational outcomes?'],
                    anchor='start',
                    subtitle='American Indians and Alaska Natives in 2023 only.',
                    # align='center',
                    fontSize=22,
                    subtitleFontSize=15,
                    dx=25)
).configure(
    font='Agency FB',
).configure_axis(
    labelFontSize=14,
    titleFontSize=16,
).configure_legend(
    titleFontSize=15,
    labelFontSize=15,
    titleAnchor='middle',
    titleAlign='center',
    orient='top-right'
)#.save('./graphics/scatter_bachelors_vs_income_byfacility.svg')

alt.Chart(...)

In [70]:
scatter_child_poverty = alt.Chart(gaming_compare23).mark_point(filled=True, opacity=0.8).encode(
    x=alt.X('hincmed_aiana').title('Median income'),
    y=alt.Y('youthpovshare_aiana').title('Percentage of youths (under 18) experiencing poverty'),
    color=alt.Color('has_facility:N').legend(
                alt.Legend(fillColor='rgba(255, 255, 255, 0.5)', 
                           cornerRadius=5,
                           padding=7,
                           title='Nation ownership')
            )#.scale(scheme='blueorange'),
    # size=alt.Size('is_facility')
)

scatter_child_poverty.properties(
    height=300,
    width=500,
    title=alt.Title(['Do wealth and gaming facility ownership correspond', 'with child poverty?'],
                    anchor='start',
                    subtitle='American Indians and Alaska Natives in 2023 only.',
                    # align='center',
                    fontSize=22,
                    subtitleFontSize=15,
                    dx=25)
).configure(
    font='Agency FB',
).configure_axis(
    labelFontSize=14,
    titleFontSize=16,
).configure_legend(
    titleFontSize=15,
    labelFontSize=15,
    titleAnchor='middle',
    titleAlign='center',
    orient='top-right'
)#.save('./graphics/scatter_youthpoverty_vs_income_byfacility.svg')

alt.Chart(...)

#### PENDING: 5 wealthiest vs 5 poorest nations and their gaming facilities / population /

In [71]:
# gaming_net_crosswalked.loc[
#     gaming_net_crosswalked['datayear']==2023,
#     :
# ]

### 8. Presence of gaming facilities and aggregate income in all reservations

In [72]:
agginc = gaming_net_crosswalked.copy()
agginc.head(2)

,owner_name,is_facility,Class II,Class II & III,Class III,Other,geoname_mostrecent,no_reservation_or_not_listed,geoid_mostrecent,geocat_mostrecent,...,perpersinc_nhopia,povshare_total,povshare_aiana,povshare_nhopia,youthpovshare_total,youthpovshare_aiana,youthpovshare_nhopia,incagg_total,source,geoname_abbrev
0,"Pueblo of Acoma, New Mexico",2.0,0.0,1.0,1.0,0.0,Acoma Pueblo and Off-Reservation Trust Land,NaN,0010,Federal Reservations/Off-Reservation Trust Lands,...,NaN,49.650892,60.264901,NaN,55.823293,55.823293,NaN,2.494565e+07,1990 decennial census and TIGER/Line shapefiles,Acoma Pueblo
1,"Pueblo of Acoma, New Mexico",2.0,0.0,1.0,1.0,0.0,Acoma Pueblo and Off-Reservation Trust Land,NaN,0010,Federal Reservations/Off-Reservation Trust Lands,...,0.0,29.769618,30.132939,NaN,32.494759,32.908705,NaN,4.356631e+07,2000 decennial census and TIGER/Line shapefiles,Acoma Pueblo

In [73]:
agginc = agginc.loc[
    ~agginc['geocat_mostrecent'].isin(['All states and commonwealths', 'United States (national)']),
    :
]
agginc['has_facility'] = np.where(agginc['is_facility']>0, 'Has facility', 'Doesn\'t have facility')
agginc23 = agginc.loc[
    agginc['datayear'].isin([1990, 2000, 2018, 2023]),
    ['owner_name', 'geoname_mostrecent', 'datayear', 'has_facility', 'incagg_total', 'pop_total']
].drop_duplicates()

In [74]:
agginc23['has_facility'].value_counts()

has_facility
Doesn't have facility    1718
Has facility              920
Name: count, dtype: int64

In [75]:
agginc23_grouped = agginc23.drop(columns=['owner_name', 'geoname_mostrecent']).groupby(['datayear', 'has_facility']).sum()
agginc23_grouped['incpercap_total'] = agginc23_grouped['incagg_total'] / agginc23_grouped['pop_total']
agginc23_grouped.reset_index(inplace=True)

In [76]:
bar_facilities = alt.Chart(agginc23_grouped).mark_bar().encode(
    x=alt.X('has_facility').title('').axis(alt.Axis(labelAngle=-45)),
    y=alt.Y('incpercap_total').title('Income per capita (all populations)'),
    facet=alt.Facet('datayear').title(''),
    color=alt.X('has_facility', legend=None).scale(scheme='set2')
)

bar_facilities.properties(
    height=300,
    width=150,
    title=alt.Title(['Has the presence of gaming facilities accompanied overall', 'reservation wealth?'],
                    anchor='start',
                    subtitle='In 2023 dollars',
                    # align='center',
                    fontSize=22,
                    subtitleFontSize=15,
                    dx=25)
).configure(
    font='Agency FB',
).configure_axis(
    labelFontSize=14,
    titleFontSize=16,
).configure_legend(
    titleFontSize=15,
    labelFontSize=15,
    titleAnchor='middle',
    titleAlign='center',
    orient='top-right'
).configure_header(
    labelFontSize=15,
)#.save('./graphics/bar_year_facet_incomepercap_vs_facility.svg')

alt.Chart(...)

In [77]:
# line_facilities = alt.Chart(agginc23_grouped).mark_line().encode(
#     x=alt.X('datayear').title(''),
#     y=alt.Y('incpercap_total').title('Income per capita (all populations)'),
#     # facet=alt.Facet('has_facility').title(''),
#     color=alt.X('has_facility', legend=None).scale(scheme='set2')
# )

# line_facilities.properties(
#     height=300,
#     width=400,
#     title=alt.Title(['Has the presence of gaming facilities accompanied overall', 'reservation wealth?'],
#                     anchor='start',
#                     subtitle='In 2023 dollars',
#                     # align='center',
#                     fontSize=22,
#                     dx=25)
# ).configure(
#     font='Agency FB',
# ).configure_axis(
#     labelFontSize=14,
#     titleFontSize=16,
# ).configure_legend(
#     titleFontSize=15,
#     labelFontSize=15,
#     titleAnchor='middle',
#     titleAlign='center',
#     orient='top-right'
# )

### End